# Generated by Django 5.2 on 2025-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_orders_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zipcode',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Address',
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=None, max_length=17),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='productImages/'),
        ),
    ]
