# Generated by Django 5.2 on 2025-06-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
